---
- name: Converge
  hosts: all
  tasks:
    - name: "Include user-management"
      include_role:
        name: "user-management"
      vars:
        manage_users:
          - user: ago
            user_passwd: 98hj3f
            groups: ""
            key: ago_id_rsa.pub
        new_root_password: 9872gh3u
